# -*- coding: utf-8 -*-
"""cipherAndDecipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LY1fKYZ3rkgVcmOV2C-LwyH6b9HKsXuP
"""

def encrypt(message,shift):
  encrypted=''
  for char in message:
    if char.isalpha():
      base =ord('A') if char.isupper() else ord('a')
      encrypted+=chr((ord(char) - base + shift)%26 + base)
    else:
      encrypted+=char
  return encrypted

def decrypt(message,shift):
  return encrypt(message,-shift)
print("---------------------------")
print("------Caesar Cipher-------")
print("---------------------------")
print(" ")

while True:
  print("Press '1' to continue")
  print("Press '0' to exit")
  print(" ")
  loop =int(input("Enter your option: "))
  print(" ")

  if loop==1:
    message=input("Enter a message: ")
    print(" ")
    print("Press 'e' to Encypt the message")
    print("Press 'd' to Decrypt the message")
    print(" ")
    choice=input("Enter your choice: ").lower()
    print(" ")
    while True:
      try:
        shift=int(input("Enter the shift value: "))
        print(" ")
        break
      except ValueError:
        print("Invalid shift value")

    if choice=="e":
      res=encrypt(message,shift)
      print(f"The encypted message is {res}")
      print("-------------------------------")
      print(" ")
    elif choice=="d":
      res=decrypt(message,shift)
      print(f"The decrypted message is {res}")
      print("-------------------------------")
      print(" ")
    else:
      print("Invalid choice")

  else:
    break

